### ISSUE TITLE
Issue with Civitai downloads

### ISSUE THREAD

**Issue by ResidentChief** [segmind/segmoe#8] opened 2024-02-05 00:22 UTC
They'll never load, code needs to be fixed to use a different diffusion pipeline that does have from_single_file available

Traceback (most recent call last):
  File "C:\Users\DonaldNixon\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\DonaldNixon\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\AI\Segmoe\Scripts\segmoe.exe\__main__.py", line 7, in <module>
  File "C:\AI\Segmoe\lib\site-packages\segmoe\cli.py", line 6, in create
    pipe = SegMoEPipeline(args[1])
  File "C:\AI\Segmoe\lib\site-packages\segmoe\main.py", line 114, in __init__
    self.load_from_scratch(config_or_path, **kwargs)
  File "C:\AI\Segmoe\lib\site-packages\segmoe\main.py", line 171, in load_from_scratch
    self.pipe = DiffusionPipeline.from_single_file(
AttributeError: type object 'DiffusionPipeline' has no attribute 'from_single_file'

**Comment by jexom** [comment] 2024-02-05 06:57
The problem is before that. Thw wget call fails because there is a missed space in the [line](https://github.com/segmind/segmoe/blob/31e8e6bc8181dc02c417c5df37d169d85483f3b3/segmoe/main.py#L166) after setting the downloaded file location.

**Comment by Warlord-K** [comment] 2024-02-08 18:04
Fixed with PR #14, Thanks for raising the issue!

**Closed by Warlord-K** 2024-02-08 18:04 UTC
